Repository Fatihayoz/javascript-quiz, pull requests merged in 2021-07, with the labels that each got.

#10 setup
  planning/backlog.md
  planning/development-strategy.md
Labels: documentation

#14 Number of questions
  client/data/quiz.js
  client/src/components/pages/home/index.js
  client/src/components/pages/home/instructions.js
  client/src/components/pages/home/number-of-questions.js
  client/src/init/state.js
  client/styles/body.css
  docs/README.md
  docs/dependency-graph.html
  docs/dependency-graph.svg
Labels: component

#16 Quiz data state setup
  client/data/quiz.js
  client/data/quiz.schema.js
  client/src/components/pages/home/index.js
  client/src/components/pages/home/number-of-questions.js
  docs/dependency-graph.html
  docs/dependency-graph.svg
Labels: JS

#18 Quiz question panel
  client/data/quiz.js
  client/src/components/pages/quiz/index.js
  client/src/components/pages/quiz/quiz-question-panel.js
  client/styles/index.css
  client/styles/quiz-question-panel.css
  docs/dependency-graph.html
  docs/dependency-graph.svg
Labels: JS

#22 Hints
  client/src/components/pages/quiz/hint-div.js
  client/src/components/pages/quiz/hint-panel.js
  client/src/components/pages/quiz/index.js
  client/src/components/pages/quiz/restart-button.js
  client/styles/index.css
  client/styles/quiz.css
  docs/README.md
  docs/dependency-graph.html
  docs/dependency-graph.svg
  index.html
Labels: CSS, JS

#25 Score
  client/data/quiz.js
  client/src/components/pages/questions/index.js
  client/src/components/pages/quiz/index.js
  client/src/components/pages/quiz/nextButton.js
  client/src/components/pages/quiz/score.js
  client/src/components/shared/input-greeting.js
  client/src/components/shared/input-greeting.test.html
  client/src/handlers/change-greeting.js
  client/src/handlers/update-score.js
  client/src/logic/reverse.js
  client/src/logic/reverse.spec.js
  docs/README.md
  docs/dependency-graph.html
  docs/dependency-graph.svg
Labels: JS, component, handler

#27 Submit
  client/data/quiz.js
  client/src/components/layout/footer.js
  client/src/components/layout/navbar.js
  client/src/components/layout/page.js
  client/src/components/pages/home/index.js
  client/src/components/pages/home/number-of-questions.js
  client/src/components/pages/quiz/div-results.js
  client/src/components/pages/quiz/hint-div.js
  client/src/components/pages/quiz/hint-panel.js
  client/src/components/pages/quiz/index.js
  client/src/components/pages/quiz/quiz-buttons.js
  client/src/components/pages/quiz/quiz-question-panel.js
  client/src/components/pages/quiz/restart-button.js
  client/src/components/pages/quiz/submit-button.js
  client/src/handlers/back-question-handler.js
  client/src/handlers/nextButtonHandler.js
  client/src/handlers/submit-button-handler.js
  client/src/init/index.js
  client/src/init/router.js
  client/src/routes.js
  docs/README.md
  docs/dependency-graph.html
  docs/dependency-graph.svg
Labels: JS, component, handler
